<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <AssemblyVersion>1.1.0.0</AssemblyVersion>
    <ApplicationIcon>..\..\..\Common\Assets\KaarinaaIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="InputSimulatorPlus" Version="1.0.7" NoWarn="NU1701" />
  </ItemGroup>

</Project>