<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.22000.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.22000.0</SupportedOSPlatformVersion>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

    <AssemblyVersion>1.18.0.0</AssemblyVersion>
    <PackageVersion>$(AssemblyVersion)</PackageVersion>

    <PackageId>Livia</PackageId>
    <Title>Livia</Title>
    <Authors>Angelina</Authors>
    <Description>
        An open-source C# automation library for building Roblox macros and applications.
    </Description>

    <PackageTags>Roblox;automation;macro;WPF;Windows;C#</PackageTags>

    <PackageLicenseExpression>MIT</PackageLicenseExpression>

    <PackageProjectUrl>https://github.com/AlinaWan/Livia</PackageProjectUrl>
    <RepositoryUrl>https://github.com/AlinaWan/Livia</RepositoryUrl>
    <RepositoryType>git</RepositoryType>

    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Copyright>Copyright (c) 2026 Angelina</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <None Include="build\Livia.props" Pack="true" PackagePath="build\" />

    <None Include="..\Livia.Analyzers\bin\$(Configuration)\netstandard2.0\Livia.Analyzers.dll" Pack="true" PackagePath="analyzers\dotnet\cs\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Livia.Analyzers\Livia.Analyzers.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />

    <None Include="Native\ScreenCapture\Livia.Native.DxgiFrameCapture.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Native\ScreenCapture\Livia.Native.DxgiFrameCapture.dll</Link>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageReference Include="System.Management" Version="10.0.12" />
  </ItemGroup>

  <Target Name="BuildScreenCapture" BeforeTargets="BeforeBuild">
    <Exec Command="powershell -NoProfile -ExecutionPolicy Bypass -File &quot;$(MSBuildProjectDirectory)\..\build-native.ps1&quot; -Configuration $(Configuration)" />
  </Target>

</Project>