name: Publish to NuGet

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      build:
        required: true
        type: string
      revision:
        required: true
        type: string
      release_name:
        required: false
        type: string
        default: ''
      prerelease:
        required: false
        type: boolean
        default: true
      dry_run:
        required: false
        type: boolean
        default: true

jobs:
  publish:
    runs-on: windows-2025-vs2026

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'

      - name: Display version
        shell: pwsh
        run: |
          Write-Host "Livia version: ${{ inputs.version }}"

      - name: Build project
        run: >
          dotnet build Livia/Livia.csproj
          -c Release
          /p:LiviaBuild=${{ inputs.build }}
          /p:LiviaRevision=${{ inputs.revision }}

      - name: Pack NuGet package
        run: >
          dotnet pack Livia/Livia.csproj
          -c Release
          --no-build
          -o ./artifacts
          /p:LiviaBuild=${{ inputs.build }}
          /p:LiviaRevision=${{ inputs.revision }}

      - name: NuGet login
        if: ${{ !inputs.dry_run }}
        uses: NuGet/login@v1
        id: nuget-login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Publish to NuGet
        if: ${{ !inputs.dry_run }}
        shell: pwsh
        run: |
          $package = Get-ChildItem ./artifacts/*.nupkg |
            Select-Object -First 1

          dotnet nuget push `
            $package.FullName `
            --source https://api.nuget.org/v3/index.json `
            --api-key "${{ steps.nuget-login.outputs.NUGET_API_KEY }}"

      - name: Create GitHub Release
        if: ${{ inputs.dry_run == false }}
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v${{ inputs.version }}
          name: ${{ inputs.release_name != '' && inputs.release_name || format('v{0}', inputs.version) }}
          generate_release_notes: true
          prerelease: ${{ inputs.prerelease }}
          files: ./artifacts/*.nupkg

      - name: Upload Workflow Artifacts (Dry Run)
        if: ${{ inputs.dry_run == true }}
        uses: actions/upload-artifact@v7
        with:
          name: nuget-package-${{ inputs.version }}
          path: |
            ./artifacts/*.nupkg
          retention-days: 7